# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{exception_logger}
  s.version = "0.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Roland Guem"]
  s.date = %q{2011-02-21}
  s.description = %q{Logs exceptions inside a database table. Now available as gem for Rails3 (previously a plugin for Rails2)}
  s.email = %q{roland.guem@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "app/controllers/logged_exceptions_controller.rb",
    "app/helpers/logged_exceptions_helper.rb",
    "app/models/logged_exception.rb",
    "app/views/layouts/logged_exceptions.html.erb",
    "app/views/logged_exceptions/_exceptions.html.erb",
    "app/views/logged_exceptions/_feed.html.erb",
    "app/views/logged_exceptions/_show.html.erb",
    "app/views/logged_exceptions/destroy.js.rjs",
    "app/views/logged_exceptions/destroy_all.js.rjs",
    "app/views/logged_exceptions/index.html.erb",
    "app/views/logged_exceptions/query.js.rjs",
    "app/views/logged_exceptions/query.xml.builder",
    "app/views/logged_exceptions/show.html.erb",
    "app/views/logged_exceptions/show.js.rjs",
    "config/initializers/date_formats.rb",
    "config/locales/en.yml",
    "config/routes.rb",
    "lib/exception_loggable_controller_mixin.rb",
    "lib/exception_logger.rb",
    "lib/exception_logger/engine.rb",
    "lib/exception_logger/exception_loggable.rb",
    "lib/generators/exception_logger/migration/migration_generator.rb",
    "lib/generators/exception_logger/migration/templates/migration.rb",
    "lib/generators/exception_logger/stylescripts/stylescripts_generator.rb",
    "lib/logged_exception_rake.rb",
    "lib/railties/tasks.rake",
    "public/javascripts/exception_logger.js",
    "public/javascripts/exception_logger_jquery.js",
    "public/stylesheets/exception_logger.css"
  ]
  s.homepage = %q{http://github.com/QuBiT/exception_logger}
  s.post_install_message = %q{
_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_
    Thank you for installing exception_logger.
    Please be sure to read the README and HISTORY on
        http://github.com/QuBiT/exception_logger
    for important information about this release. Happy logging!
_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_
    }
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Exception Logger for Rails 3}
  s.test_files = [
    "test/controllers/logged_exceptions_controller_test.rb",
    "test/models/logged_exception_test.rb",
    "test/rails_root/Gemfile",
    "test/rails_root/Gemfile.lock",
    "test/rails_root/app/controllers/application_controller.rb",
    "test/rails_root/test/factories/exception_logger.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<shoulda>, [">= 2.11.3"])
      s.add_runtime_dependency(%q<factory_girl_rails>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4.3.1"])
      s.add_runtime_dependency(%q<capybara>, [">= 0.3.9"])
      s.add_runtime_dependency(%q<database_cleaner>, [">= 0.5.2"])
      s.add_runtime_dependency(%q<cucumber-rails>, [">= 0.3.2"])
      s.add_runtime_dependency(%q<cucumber>, [">= 0.8.5"])
      s.add_runtime_dependency(%q<launchy>, [">= 0.3.7"])
      s.add_runtime_dependency(%q<will_paginate>, [">= 3.0.pre2"])
      s.add_runtime_dependency(%q<meta_where>, [">= 0.5.2"])
      s.add_runtime_dependency(%q<i18n>, [">= 0.4.1"])
      s.add_runtime_dependency(%q<exception_logger>, [">= 0"])
      s.add_runtime_dependency(%q<rails>, [">= 3.0"])
      s.add_runtime_dependency(%q<will_paginate>, [">= 3.0.pre2"])
      s.add_runtime_dependency(%q<meta_where>, [">= 0.5.2"])
      s.add_runtime_dependency(%q<i18n>, [">= 0.4.1"])
      s.add_development_dependency(%q<shoulda>, [">= 2.11.3"])
    else
      s.add_dependency(%q<rails>, ["= 3.0.0.rc"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 2.11.3"])
      s.add_dependency(%q<factory_girl_rails>, [">= 1.0.0"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.3.1"])
      s.add_dependency(%q<capybara>, [">= 0.3.9"])
      s.add_dependency(%q<database_cleaner>, [">= 0.5.2"])
      s.add_dependency(%q<cucumber-rails>, [">= 0.3.2"])
      s.add_dependency(%q<cucumber>, [">= 0.8.5"])
      s.add_dependency(%q<launchy>, [">= 0.3.7"])
      s.add_dependency(%q<will_paginate>, [">= 3.0.pre2"])
      s.add_dependency(%q<meta_where>, [">= 0.5.2"])
      s.add_dependency(%q<i18n>, [">= 0.4.1"])
      s.add_dependency(%q<exception_logger>, [">= 0"])
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<will_paginate>, [">= 3.0.pre2"])
      s.add_dependency(%q<meta_where>, [">= 0.5.2"])
      s.add_dependency(%q<i18n>, [">= 0.4.1"])
      s.add_dependency(%q<shoulda>, [">= 2.11.3"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.0.0.rc"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 2.11.3"])
    s.add_dependency(%q<factory_girl_rails>, [">= 1.0.0"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.3.1"])
    s.add_dependency(%q<capybara>, [">= 0.3.9"])
    s.add_dependency(%q<database_cleaner>, [">= 0.5.2"])
    s.add_dependency(%q<cucumber-rails>, [">= 0.3.2"])
    s.add_dependency(%q<cucumber>, [">= 0.8.5"])
    s.add_dependency(%q<launchy>, [">= 0.3.7"])
    s.add_dependency(%q<will_paginate>, [">= 3.0.pre2"])
    s.add_dependency(%q<meta_where>, [">= 0.5.2"])
    s.add_dependency(%q<i18n>, [">= 0.4.1"])
    s.add_dependency(%q<exception_logger>, [">= 0"])
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<will_paginate>, [">= 3.0.pre2"])
    s.add_dependency(%q<meta_where>, [">= 0.5.2"])
    s.add_dependency(%q<i18n>, [">= 0.4.1"])
    s.add_dependency(%q<shoulda>, [">= 2.11.3"])
  end
end

