# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "r3_exception_logger"
  s.version = "0.1.13"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Roland Guem"]
  s.date = "2012-05-26"
  s.description = "Logs exceptions inside a database table. Now available as gem for Rails3 (previously a plugin for Rails2)"
  s.email = "roland.guem@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "app/controllers/logged_exceptions_controller.rb",
    "app/helpers/logged_exceptions_helper.rb",
    "app/models/logged_exception.rb",
    "app/views/layouts/logged_exceptions.html.erb",
    "app/views/logged_exceptions/_exceptions.html.erb",
    "app/views/logged_exceptions/_feed.html.erb",
    "app/views/logged_exceptions/_show.html.erb",
    "app/views/logged_exceptions/destroy.js.erb",
    "app/views/logged_exceptions/destroy_all.js.erb",
    "app/views/logged_exceptions/feed.rss.builder",
    "app/views/logged_exceptions/index.html.erb",
    "app/views/logged_exceptions/index.js.erb",
    "app/views/logged_exceptions/query.js.erb",
    "app/views/logged_exceptions/show.html.erb",
    "app/views/logged_exceptions/show.js.erb",
    "config/initializers/date_formats.rb",
    "config/locales/en.yml",
    "config/routes.rb",
    "lib/exception_loggable_controller_mixin.rb",
    "lib/exception_logger.rb",
    "lib/exception_logger/engine.rb",
    "lib/exception_logger/exception_loggable.rb",
    "lib/generators/exception_logger/migration/migration_generator.rb",
    "lib/generators/exception_logger/migration/templates/migration.rb",
    "lib/generators/exception_logger/stylescripts/stylescripts_generator.rb",
    "lib/logged_exception_rake.rb",
    "lib/railties/tasks.rake",
    "public/javascripts/exception_logger.js",
    "public/stylesheets/exception_logger.css"
  ]
  s.homepage = "http://github.com/QuBiT/exception_logger"
  s.post_install_message = "\n_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_\n    Thank you for installing exception_logger.\n    Please be sure to read the README and HISTORY on\n        http://github.com/QuBiT/exception_logger\n    for important information about this release. Happy logging!\n_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_()_\n    "
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.16"
  s.summary = "Exception Logger for Rails 3"
  s.test_files = ["test/controllers", "test/controllers/logged_exceptions_controller_test.rb", "test/models", "test/models/logged_exception_test.rb", "test/rails_root", "test/rails_root/app", "test/rails_root/app/controllers", "test/rails_root/app/controllers/application_controller.rb", "test/rails_root/Gemfile", "test/rails_root/Gemfile.lock", "test/rails_root/test", "test/rails_root/test/factories", "test/rails_root/test/factories/exception_logger.rb", "test/test_helper.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
      s.add_runtime_dependency(%q<kaminari>, [">= 0"])
      s.add_runtime_dependency(%q<squeel>, [">= 0"])
      s.add_runtime_dependency(%q<i18n>, [">= 0.4.1"])
      s.add_development_dependency(%q<shoulda>, [">= 2.11.3"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<kaminari>, [">= 0"])
      s.add_dependency(%q<squeel>, [">= 0"])
      s.add_dependency(%q<i18n>, [">= 0.4.1"])
      s.add_dependency(%q<shoulda>, [">= 2.11.3"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<kaminari>, [">= 0"])
    s.add_dependency(%q<squeel>, [">= 0"])
    s.add_dependency(%q<i18n>, [">= 0.4.1"])
    s.add_dependency(%q<shoulda>, [">= 2.11.3"])
  end
end

